sudo: required
services:
        - docker

before_install:
        - echo 'Running build automation'
        - sh './gradlew build --no-daemon'
        - archiveArtifacts artifacts: 'dist/trainSchedule.zip'
    
script:
        - docker run -e CI=true hm3cheun/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "react-docker"
    env: "ReactDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-831687209203"
    bucket_path: "react-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
